-- Auto-generated from schema-map-postgres.yaml (map@94ebe6c)
-- engine: postgres
-- table:  order_item_downloads

CREATE TABLE IF NOT EXISTS order_item_downloads (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT NOT NULL,
  order_id BIGINT NOT NULL,
  book_id BIGINT NOT NULL,
  asset_id BIGINT NOT NULL,
  download_token_hash BYTEA NULL,
  token_key_version VARCHAR(64) NULL,
  key_version VARCHAR(64) NULL,
  max_uses INTEGER NOT NULL,
  used INTEGER NOT NULL DEFAULT 0,
  is_active BOOLEAN GENERATED ALWAYS AS (used < max_uses) STORED,
  expires_at TIMESTAMPTZ(6) NOT NULL,
  last_used_at TIMESTAMPTZ(6) NULL,
  ip_hash BYTEA NULL,
  ip_hash_key_version VARCHAR(64) NULL
);
